
class CfgPatches {
	class AL_Anims {
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.100000;
		requiredAddons[] = { "A3_Anims_F" };
	};
};

/*extern*/ class CfgMovesBasic;
class AL_CfgMovesMaleSdr : CfgMovesBasic {
	class States {
		class AmovPercMstpSnonWnonDnon_Restrained {
			access = 3;
			actions = "CivilStandSaluteActions";
			adjstance = "m";
			affectedByFatigue = "false";
			aiming = "aimingCivil";
			aimingBody = "aimingUpCivil";
			aimPrecision = 1;
			boundingSphere = 1;
			camShakeFire = 1;
			canBlendStep = 1;
			canPullTrigger = 0;
			canReload = 1;
			collisionShape = "A3\anims_f\Data\Geom\Sdr\Perc_Wnon.p3d";
			collisionShapeSafe = "";
			connectAs = "";
			connectFrom[] = {};
			connectTo[] = {};
			disableWeapons = 1;
			disableWeaponsLong = 1;
			duty = -0.8;
			enableAutoActions = 0;
			enableBinocular = 0;
			enableDirectControl = 1;
			enableMissile = 0;
			enableOptics = 0;
			equivalentTo = "";
			file = "\A3\anims_f\Data\Anim\Sdr\mov\erc\stp\non\non\AmovPercMstpSnonWnonDnon_Ease";
			forceAim = 1;
			GetOutPara = "";
			hasCollShapeSafe = 0;
			head = "headNo";
			headBobMode = 5;
			headBobStrength = -1;
			idle = "idleDefault";
			ignoreMinPlayTime[] = { "Unconscious" };
			interpolateFrom[] = {};
			InterpolateTo[] = { "Unconscious",0.01 };
			interpolateWith[] = {};
			interpolationRestart = 0;
			InterpolationSpeed = 2.5;
			leaning = "leaningDefault";
			leaningFactorBeg = 0;
			leaningFactorEnd = 0;
			leaningFactorZeroPoint = -1;
			leftHandIKBeg = 0;
			leftHandIKCurve[] = {};
			leftHandIKEnd = 0;
			legs = "legsDefault";
			limitGunMovement = 0.3;
			looped = 1;
			minPlayTime = 0;
			onLadder = 0;
			onLandBeg = 0;
			onLandEnd = 0;
			preload = 0;
			ragdoll = 0;
			relSpeedMax = 1;
			relSpeedMin = 1;
			rightHandIKBeg = 0;
			rightHandIKCurve[] = {};
			rightHandIKEnd = 0;
			showHandGun = 0;
			showItemInHand = 0;
			showItemInRightHand = 0;
			showWeaponAim = 0;
			soundEdge[] = { 0.01 };
			soundEnabled = 1;
			soundOverride = "";
			speed = 10000000000.000000;
			static = 1;
			terminal = 0;
			useIdles = 1;
			variantAfter[] = { 45,45,45 };
			variantsAI[] = { "" };
			variantsPlayer[] = {};
			visibleSize = 0.75012;
			Walkcycles = 1;
			weaponIK = 0;
			weaponLowered = 1;
		};
	};
};